### ISSUE TITLE
co-body security with qs

### ISSUE THREAD

**Issue by andresilvagomez** [adonisjs/adonis-middleware#11]
Currently you are using [co-body](https://github.com/cojs/co-body) with version 4.2.0, this include [qs](https://github.com/ljharb/qs) in version 4.0.0, which is [vulnerable](https://snyk.io/vuln/npm:qs:20170213), https://snyk.io/vuln/npm:qs:20170213

The solution is upgrade the [co-body](https://github.com/cojs/co-body) version to latest.

Could you upgrade this?

Thanks 👍

**Comment by thetutlage** [comment]
Thanks and merged
