### ISSUE TITLE
Exporting factory function from middleware

### ISSUE THREAD

**Issue by xxzefgh** [adonisjs/adonis-middleware#14]
Hello,
I wanted to serve static files from one more directory, so I created middleware for that and copied code from official static [middleware](https://github.com/adonisjs/adonis-framework/blob/develop/src/Static/index.js), but it didn't work (`E_UNDEFINED_METHOD: Method handle missing on ...`). I guess error came from exporting factory function rather than middleware class itself. To solve that, I implemented static server mounting function inside middleware like that:
```js
  async handle({ request, response }, next) {
    this.mountStaticServer()
    ...
  }

  mountStaticServer() {
    /**
     * Mount the static server if not already mounted
     */
    if (!staticServer) {
      const options = Config.merge('app.static', defaultConfig)
      options.fallthrough = false
      staticServer = Helpers.promisify(
        serveStatic(Helpers.publicPath('dist'), options)
      )
    }
  }
```

It works as expected, but I'm concerned if this method has any performance drawbacks.
Thanks.

**Comment by thetutlage** [comment]
I believe if you implement it exactly the same way it's done in the official implementation, then it will be fine https://github.com/adonisjs/adonis-framework/blob/develop/src/Static/index.js

The best I can suggest is to even avoid creating a new middleware and instead symlink your dist directory inside `public` directory.

```js
ln -s dist public/dist
```

And then access the files as `BASE_URL/dist/FILE_NAME`

**Comment by xxzefgh** [comment]
It won't work, because builtin static middleware is treated differently [here](https://github.com/adonisjs/adonis-framework/blob/develop/providers/AppProvider.js#L181-L186)
but I'm not sure where can I get app instance to do the same, can you point me where is the correct place to put that code?

**Comment by xxzefgh** [comment]
I ended up registering middleware in `kernel.js`
```js
const { ioc } = require('@adonisjs/fold')

ioc.bind('App/Middleware/StaticDist', (app) => {
  const StaticDist = require('../app/Http/Middleware/StaticDist')
  return StaticDist(app.use('Adonis/Src/Helpers'), app.use('Adonis/Src/Config'))
})
```
