### ISSUE TITLE
[Question] should middleware components have their own packages?

### ISSUE THREAD

**Issue by MilkyWayJoe** [adonisjs/adonis-middleware#4]
Hi. Just a question in regards to the middleware: Are there any plans to release them in separate npm packages? If no, why not? if yes, is there any previous discussion about it? (couldn't find it). Also, would this be something I could help with?

**Comment by thetutlage** [comment]
why they should be different npm packages?

**Comment by MilkyWayJoe** [comment]
I asked more out of curiosity, as I'm still researching different frameworks. As for my question, I don't know that they should be separate packages, but for example, in the event that I build an app that does not use CORS, I don't need those bits in my project, and as it stands I will have them regardless of using it, which is no big deal now, but what's gonna happen when this repo starts hosting 10+ different middleware, for different things?
So one benefit of publishing separate packages for middleware would be essentially _modularizing_ further the integration of middleware within a given app. 
Not trying to draw comparisons here, but another benefit I see in publishing separate packages for middleware is to achieve something akin from Ember Addons infrastructure, in the sense that each new middleware package can be tagged as such, rated, and a semi-centralized list of components could be easily found by community members.

**Comment by RomainLanz** [comment]
Hey @MilkyWayJoe,

> I don't need those bits in my project, and as it stands I will have them regardless of using it, which is no big deal now, but what's gonna happen when this repo starts hosting 10+ different middleware, for different things?

You can still remove them from loading if you change the `app/Http/kernel.js` file.

**Comment by MilkyWayJoe** [comment]
@RomainLanz not what I meant. Loading the middleware into the application is pretty transparent currently. I wasn't talking about the _built app_ but rather the dev environment. Ember Addons built with their CLI (https://www.emberaddons.com/) are essentially what I had in mind when I opened this question.  The way these addons (which can be a simple helper or an entire sub-project) are created, could be somehow be reproduced for Adonis middleware.

**Comment by thetutlage** [comment]
Now they have. 

1. [adonis-bodyparser](https://github.com/adonisjs/adonis-bodyparser)
1. [adonis-shield](https://github.com/adonisjs/adonis-shield)
1. [adonis-cors](https://github.com/adonisjs/adonis-cors)
